name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pytest pytest-junitxml
          pip install -r requirements.txt

      - name: Install WebDriver and Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          python -m selenium.webdriver.chrome.service

      - name: Run Selenium tests with Pytest
        run: pytest tests/ --junitxml=reports/test-results.xml --junit-suite-name="Github_Actions_Selenium_Tests"

      - name: Encode test results and send to Pulse
        if: always()
        run: |
          ENCODED_RESULTS=$(base64 -w 0 reports/test-results.xml)
          curl -X POST "$PULSE_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d "{\"result\":\"$ENCODED_RESULTS\",\"projectId\":\"136384\",\"testcycle\":\"5867465\"}"
        env:
          PULSE_WEBHOOK_URL: "https://pulse-7.qtestnet.com/webhook/6f62bf7c-8fde-4835-8ace-2f1d90c62a37"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-results
          path: reports/
