name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install WebDriver and Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          # Use selenium-manager to handle the ChromeDriver version automatically
          python -m selenium.webdriver.chrome.service

      - name: Run Selenium tests with Pytest
        run: pytest tests/ --junitxml=reports/test-results.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-results
          path: reports/
